### ISSUE TITLE
Error when using -MasterKey parameter with functions

### ISSUE THREAD

**Issue by Cavorter** [PSKeePass/PoShKeePass#100] opened 2016-11-29 19:40 UTC
When specifying the -MasterKey parameter with any function I get some variant on the following error:

```
PS C:> Get-KeePassGroup -DatabaseProfileName SomeConfig -KeePassGroupPath some/path -MasterKey $aSecureString
Remove-Variable : Cannot find a variable with the name 'KeePassCredentialObject'.
At <modulepath>\PoShKeePass\2.0.3.1\PoShKeePass.psm1:657 char:28
+ ...         if($MasterKey){Remove-Variable -Name KeePassCredentialObject}
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (KeePassCredentialObject:String) [Remove-Variable], ItemNotFoundException
    + FullyQualifiedErrorId : VariableNotFound,Microsoft.PowerShell.Commands.RemoveVariableCommand
```

The error does not happen when I do not specify the -MasterKey parameter and get prompted for the value.

Just looking through the code it looks like you're already doing cleanup for that variable inside Invoke-KPConnection but from the check-in history it looks like you're doing some other work on that area of functionality so it's unclear if submitting a PR to remove the extraneous Remove-Variable calls would be useful or not.

**Comment by jkdba** [comment] 2016-11-29 19:57
Thanks for the find, the issue is that it should be removing the masterkey variable and not the KeePassCredentialObject which does not exist in the scope of any of these functions. 

It only happens when you specify the parameter because the masterkey variable does not exist in the begin block when it prompts you for the password.

I will clean up the bad copy and paste and package it into the next release, along with some smarter clean up.

**Comment by jkdba** [comment] 2016-11-29 20:05
This has been added to the Dev Branch and will be part of the next release. I will leave this open until I roll out the code.

**Comment by Cavorter** [comment] 2016-11-29 20:11
Thanks so much for the super fast response. Out of curiosity (and not at _all_ to pressure you or anything) but what does your timeline look like for the next release? Just want to have an idea so I can plan for some work I'm doing on an internal project that I'm hoping to use your module with.

**Comment by jkdba** [comment] 2016-11-29 22:13
@Cavorter, well right now is a busy time because of the holidays and I have some extra travel planned but I would say hopefully within the next couple of weeks. I will look into wrapping up and writing tests for the changes I have now and potentially will release much sooner. I will keep you posted.

**Comment by jkdba** [comment] 2016-12-06 20:22
This Fix has been released. 
@Cavorter  you will find this fix in the master branch as well as on the PSGallery.

**Closed by jkdba** 2016-12-06 20:22 UTC
Labels: bug, Code-Cleanup, Known-Issue
